### ISSUE TITLE
Eureka!  AppleScript can pause/un-pause Dropbox syncing.

### ISSUE THREAD

**Issue by JohnSauer** [tjluoma/dropbox-pause-unpause#2]
In response to:
> There is no way to properly pause/un-pause the Dropbox Mac app via scripting. Doing so would select the Dropbox menu bar item and then the appropriate menu item. So far, no one has found a reliable way to do that.

Today I found a reliable way to pause/un-pause via AppleScript UI scripting.  Like all UI scripting, it will eventually need reevaluation when Dropbox's developers decide to change the user interface.

    tell application "System Events" to tell process "Dropbox"
        click menu bar 2's menu bar item 1
        set popOver to window 1's pop over 1
        (*
            Button 1 is the bottommost button, which pauses and resumes syncing.
            When it does not have keyboard focus, it displays the current state of syncing, such as "Syncing paused" or "Syncing 20 files".  In this state, clicking it does nothing.
            When it does have keyboard focus, it displays what the state of syncing will change to if it's clicked.  In this state, clicking it toggles syncing on and off.
            So, in order for UI scripting to use this button to toggle syncing on and off, it must first be given keyboard focus.
        *)
        set popOver's button 1's attribute "AXFocused"'s value to true
        click popOver's button 1
        click menu bar 2's menu bar item 1
    end tell

**Comment by tjluoma** [comment]
Unfortunately this doesn't seem to work for me. It opens <https://www.dropbox.com/h> but does not seem to pause syncing.

**Comment by JohnSauer** [comment]
Interesting.  Would you try changing all "popOver's button 1" to "popOver's button 2", or 3, etc?

For whatever reason, your Mac considers button 1 to be the "Open Dropbox website" (![dropbox-website](https://user-images.githubusercontent.com/3065397/53614874-6e723100-3ba9-11e9-83ea-bf8df656e9a7.png)) button, while for me button 1 is the "Pause syncing" button.

**Comment by tjluoma** [comment]
I tried the original again on my Mac Mini, and this time I get a different result: it opened the Dropbox menu from the menu bar, and then showed the "Gear Icon" menu -- but did not pause syncing.

I tried changing it to "set popOver to window 1's pop over 2" and got this result:

> System Events got an error: Can’t get pop over 2 of window 1 of process "Dropbox". Invalid index.

**_However_** when I tried the original AppleScript on my MacBook -- it worked.

So, what's the difference between the two computers?

The Mac Mini is running High Sierra and Dropbox version 68.3.95.

The MacBook is running Mojave and Dropbox version 67.4.83.

I tried it on my old iMac running El Cap and Dropbox 67.4.83 -- and it worked.

That led me to believe that the difference was not the version of Mac OS, but the version of Dropbox.

Now, I have no idea why my Mac Mini is running a different version of Dropbox, but I happened to have the Dropbox-67.4.83.dmg file, so I reinstalled that version on my Mac Mini.

And then the AppleScript worked!

So the good news is that YES this works…

The bad news is that it does not seem like it will work for very long, assuming that 68.3.95 and following will break it ☹️ 

_edited to add:_  You can get the newer version of Dropbox at:

<https://clientupdates.dropboxstatic.com/dbx-releng/client/Dropbox%2068.3.95.dmg>

It is a beta build so maybe the actual non-beta release will work?

**Comment by JohnSauer** [comment]
My approach is UI scripting, so inevitably some future Dropbox release will break it.  If it's any consolation, now that I'm using this AppleScript myself, I'm invested in maintaining it to continue working with Dropbox's latest GA release.

**Comment by varenc** [comment]
This Applescript works fine for me! Generated with some help of Automator's "record my action" feature.  By specifying each menu item's name it should be resilient to Dropbox re-ordering things.


```applescript
tell application "System Events"
  -- Pause syncing
	click menu bar item 1 of menu bar 2 of application process "Dropbox"
	click menu item "Pause Syncing" of menu 1 of menu bar item 1 of menu bar 2 of application process "Dropbox"
	
	delay 2
	-- Now re-enable syncing
	click menu bar item 1 of menu bar 2 of application process "Dropbox"
	click menu item "Resume Syncing" of menu 1 of menu bar item 1 of menu bar 2 of application process "Dropbox"
end tell
```

[Now in a gist here](https://gist.github.com/varenc/81088c29a4e21e1cfe79ed321599c9b5)
